version: '3.1'

services:
  rails:
    build: .
    container_name: tropy-rails
    ports:
      - "3000:3000"
    environment:
      TZ: Asia/Tokyo
      RAILS_ENV: production
      DATABASE_PASSWORD: postgres
      RAILS_SERVE_STATIC_FILES: '1'
    volumes:
      - ./config/credentials.yml.enc:/app/config/credentials.yml.enc
      - ./config/master.key:/app/config/master.key
      - ./log:/app/log

  db:
    image: postgres:14.3
    container_name: tropy-db
    environment:
      TZ: Asia/Tokyo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tropy
